name: Gradle Run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-output-${{ matrix.modules.name }}-${{ matrix.os }}
          path: |
            test-output/output.json
            test-output/HtmlReport/ExtentHtml.html
            target/surefire-reports/junitreports/*.xml
      - name: Observe artifacts
        run: |
          pwd
          ls -l
      - name: Download Test Reports Folder
        uses: actions/download-artifact@v2
        with:
          name: test-output-${{ matrix.modules.name }}-${{ matrix.os }}
      - name: Observe artifacts
        run: |
          pwd
          mkdir test-results
          cp target/surefire-reports/junitreports/TEST-com.huma.runner.MobileRunner.xml test-results/${{ matrix.modules.name }}-${{ matrix.os }}.xml
          cp test-output/output.json test-results/output.json
